### ISSUE TITLE
MODULE_NOT_FOUND Error

### ISSUE THREAD

**Issue by subhadeepbiswas** [sphereio/sphere-node-cli#154]
### Description
The issue is coming when trying to run npm package installation globally
`npm install -g sphere-node-cli`

### Expected Behavior
It should install the **sphere-node-cli** package globally.

### Current Behavior
It is throwing a MODULE NOT FOUND error.

**Please find below error also attached the log file**

sphere-node-cli@3.0.2 preinstall /usr/local/lib/node_modules/sphere-node-cli
 node safe-resolution-check.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/usr/local/lib/node_modules/sphere-node-cli/safe-resolution-check.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
sphere-stock-import@3.0.5 preinstall /usr/local/lib/node_modules/sphere-node-cli/node_modules/sphere-stock-import
node safe-resolution-check.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sphere-node-cli@3.0.2 preinstall: `node safe-resolution-check.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sphere-node-cli@3.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
[2020-08-25T15_07_34_349Z-debug.log](https://github.com/sphereio/sphere-node-cli/files/5124720/2020-08-25T15_07_34_349Z-debug.log)

### Context
It is not allowing to use the cli tool to import.

**Comment by VineetKumarKushwaha** [comment]
I got the problem. Soon will be fixing in the next version.
