### ISSUE TITLE
Match by channel by key instead of id

### ISSUE THREAD

**Issue by emmenko** [sphereio/sphere-node-cli#17]
@hajoeichler can you describe here what you meant?

**Comment by hajoeichler** [comment]
Where is the source of this ticket?

**Comment by hajoeichler** [comment]
I edited the title.
We want to provide the possibility to only pass the key of a channel. The tooling then has the find the corresponding sphere-id to do the actually POST call.

**Comment by hajoeichler** [comment]
I think this issue has to be solved by the stock-importer, or @emmenko ?

**Comment by emmenko** [comment]
Yep
