### ISSUE TITLE
provide example payload for product creation

### ISSUE THREAD

**Issue by emtii** [sphereio/sphere-node-cli#23]
Could you please provide an example payload for using sphere-import to create new products? Including nested attributes, please.

Additionally, could you please extend your manpage with available types to choose from for import?

>> -t, --type <name>    type of import

**Comment by emmenko** [comment]
> Could you please provide an example payload for using sphere-import to create new products? Including nested attributes, please.

Please open an issue here https://github.com/sphereio/sphere-product-import

> Additionally, could you please extend your manpage with available types to choose from for import?

That I can do :)

**Comment by emmenko** [comment]
Done, I've also released a new version https://github.com/sphereio/sphere-node-cli/releases/tag/v0.3.0
