### ISSUE TITLE
.error:   Skipping product due to error message: New product name must not be empty or equal to the old name.

### ISSUE THREAD

**Issue by emtii** [sphereio/sphere-node-cli#26]
Hi,

well... ive got 5 data sources to build the json for a product import actually and it does not look like its getting less.

So I just tried to update my aggregated product import json with a new product title as the customer has new titles in another database I have to use. So i connected it, updated my json with the new field and... hoped I could just import my new json by this CLI. 

its not using the update action actually, isn't it? Do I have to write my own update-process for updating product titles actually or is there a way with this CLI? 

Thanks for Feedback.

BR
Emtii

**Comment by emmenko** [comment]
Can you post your json and the entire output + error message? It would help to debug the problem.

**Comment by emtii** [comment]
Thank you - I was able to find the problem myself, sometimes its just a night of sleep what helps. Thanks for the fast supprt!

**Comment by hajoeichler** [comment]
Can you give us some information please, how you solved it. Just for the next one stumbling over the same problem ;)

**Comment by emmenko** [comment]
:+1:

**Comment by emtii** [comment]
The error message was a bit misleading. I needed to make sure the product title is exactly the old one so sphere does not make an update. NULL is not allowed in there aswell as leaving the title in general, too. It has to be exactly the same title as before to make it work. I assume this counts for every other field.

**Comment by hajoeichler** [comment]
@sebbulon can you please create a ticket for our API. thx!
