### ISSUE TITLE
payload -t stock

### ISSUE THREAD

**Issue by emtii** [sphereio/sphere-node-cli#27]
Hi,

currently I face some issues with the payload for stock. This is what I generate:

    {
        "stocks": [
            {
                "sku": "4001513102164",
                "quantity": 85
            },
            {
                "sku": "4001513102423",
                "quantity": 28
            }
        ]
    }

What is wrong with that? Getting:

.Unhandled rejection BadRequest: Request body does not contain valid JSON.

**Comment by emmenko** [comment]
I'll have a look

**Comment by emmenko** [comment]
@emtii I've released a new version that should give you a better error log. Can you try with that?

```bash
npm i -g sphere-node-cli@0.3.2
```

**Comment by emtii** [comment]
```
{ statusCode: 400,
  message: 'Request body does not contain valid JSON.',
  errors: 
   [ { code: 'InvalidJsonInput',
       message: 'Request body does not contain valid JSON.',
       detailedErrorMessage: 'quantityOnStock: Missing required value' } ],
  originalRequest: 
   { endpoint: '/inventory',
     payload: { sku: '4001513102423', quantity: 11 } } }
```

Top! Danke dafür - das ist mal eine vernünftige Error-Message. So richtig verstehe ich es nicht, denn 

https://github.com/sphereio/sphere-json-schemas/blob/master/examples/stock/with-channel.json
https://github.com/sphereio/sphere-json-schemas/blob/master/schema/stock.schema.json

kennt dieses Feld quantityOnStock anscheinend noch nicht... wie müsste mein Payload also genau aussehen?

**Comment by emtii** [comment]
For everyone facing the same issue like me do, heres the payload what works on the date i post this comment:

``` 
{
    "stocks": [
        {
            "sku": "4001513102164",
            "quantityOnStock": 85
        },
        {
            "sku": "4001513102423",
            "quantityOnStock": 28
        }
    ]
}
```

**Comment by emmenko** [comment]
You're right, the schema is probably wrong. We will fix that. Sorry for the trouble!

/cc @hajoeichler @panshul007

**Comment by emmenko** [comment]
@emtii I've opened an issue https://github.com/sphereio/sphere-json-schemas/issues/19
