### ISSUE TITLE
product update fails if product is in a category

### ISSUE THREAD

**Issue by CT-Szilvia** [sphereio/sphere-node-cli#34]
If I try to import a json file to update a product which is already in a category I get following error message:

error: Skipping product due to error message: Cannot add to category '7bcad580-c785-4b29-9f72-960436ccc186' because the product 'LocalizedString(Map(en -> Vest))' is already in that category. 

I try to update simple fields like name, description etc... informations which will be transformed from csv to a json by the product transformer.
We are not updating categories, so it can't be a problem. 

So not sure why it can't import products which has already categories. 

If you need more informations, please let me know. 
Many thanks & regards,
Szilvia

**Comment by emmenko** [comment]
@CT-Szilvia no links to private repos please (I've removed it). 

Also can you open the issue in the product-import repo? Thanks.

**Comment by CT-Szilvia** [comment]
Ok, thanks @emmenko!

**Comment by emmenko** [comment]
https://github.com/sphereio/sphere-product-import/issues/47
