### ISSUE TITLE
rebrand before it has wide adoption

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-node-cli#38]
Hi, 

as this new CLI is not yet widely used outside the company that is a chance to change the SPHERE branding.    Once it's in wide use we're stuck again.  Now that commercetools is getting more consitent, the remaining sphere monikers are really starting to create confusion with users.  I start to get asked, what the "sphere" thing is more and more since ca. one month. 

we bit the bullet in the PHP SDK and it turned out to be not as bad as expected once we took the heart to really and fully do it.

**Comment by emmenko** [comment]
How should that be rebranded? `sphere` -> `commercetools`?

**Comment by emmenko** [comment]
That also mean, package name, binaries and so on?

**Comment by nkuehn** [comment]
If possible yes.  But I have no idea of how deeply intertwingled the stuff is with other projects etc. 

As a bare minimum the documentation, binary name, config files and parameter names would be very nice, so that a commandline user does not have to know that this product was "formerly known as".

**Comment by nkuehn** [comment]
(about your first question) specific naming is Hajos domain.  Most stuff I saw rebranded went  from all variants of `sphere`, `sphereio`, `sphere.io`,  `SPHERE.IO`  to just `commercetools`  (no .io,  no platform).
