### ISSUE TITLE
Define how to read SPHERE credentials

### ISSUE THREAD

**Issue by emmenko** [sphereio/sphere-node-cli#5]

**Comment by yanns** [comment]
It would be good to be able to read the secret from an OS environment variable.

**Comment by emmenko** [comment]
Good idea!

**Comment by hajoeichler** [comment]
Why not simply reusing what we have: https://github.com/sphereio/sphere-node-utils/blob/master/src/coffee/helpers/project-credentials-config.coffee

**Comment by svenmueller** [comment]
+1 for OS environment variable (e.g. to override stuff defined in config file)

**Comment by emmenko** [comment]
I will enhance it, just wanted to keep it as simple as possible for now :)

**Comment by emmenko** [comment]
So this is how it works now ;)

https://github.com/sphereio/sphere-node-cli/blob/da289458d05bbbc634d6e52c792ceb98ce98ee21/src/utils/help.coffee

**Comment by yanns** [comment]
:+1:
