### ISSUE TITLE
Add support for discount codes

### ISSUE THREAD

**Issue by wizzy25** [sphereio/sphere-node-cli#64]
### Description

As part of [this project](https://github.com/commercetools/nodejs/projects/2) and #143, add documentation for discount code importer #171
This will be implemented when `143-code-import-main` gets merged to Master

**Comment by hisabimbola** [comment]
Is this still blocked?

**Comment by wizzy25** [comment]
Will be put on hold until [this](/commercetools/nodejs/pull/209) gets merged.

**Comment by hisabimbola** [comment]
any update @wizzy25 ?

**Comment by wizzy25** [comment]
Yeah... In review #68
